"""Narrow immutable projection supplied by the Product composition root."""

from __future__ import annotations

from pathlib import Path
from typing import Protocol

from mote.runtime.agent.components.action import ActionComponentInputs
from mote.runtime.agent.components.cognition import CognitionComponentInputs
from mote.runtime.agent.components.context import ContextComponentInputs
from mote.runtime.agent.components.integrations import IntegrationComponentInputs
from mote.runtime.agent.components.policy import PolicyComponentInputs
from mote.runtime.agent.components.session import SessionComponentInputs
from mote.runtime.agent.components.watching import WatchingComponentInputs


class AgentComponentProjection(Protocol):
    """Only the composition root may expand Product resources into component inputs."""

    def action(self) -> ActionComponentInputs: ...
    def cognition(self) -> CognitionComponentInputs: ...
    def context(self) -> ContextComponentInputs: ...
    def integrations(self) -> IntegrationComponentInputs: ...
    def policy(self) -> PolicyComponentInputs: ...
    def session(self) -> SessionComponentInputs: ...
    def watching(self) -> WatchingComponentInputs: ...
    def watched_config_paths(self) -> list[str]: ...
    def user_config_root(self) -> Path: ...
    def session_workspace_root(self) -> Path: ...


__all__ = ["AgentComponentProjection"]
