"""common.events — the unified agent event spine.

One ordered async stream: producers ``emit`` events, subscribers consume them in
priority order. Converges three concerns (stream sink, session recorder, hook
fire-sites) onto a single decoupled bus.

Public surface:
  * :class:`EventBus` + the active-bus contextvar (:func:`set_bus` /
    :func:`current_bus` / :func:`observe_event` / :func:`observe_event_sync`).
    The contextvar entrypoints are **observation-only** — control reaches the bus
    through an explicit emitter-held reference, never the ambient contextvar.
  * The :mod:`~mote.common.events.types` tagged-union event dataclasses.
  * The :mod:`~mote.common.events.outcomes` typed per-event control outcomes.
"""

from mote.common.events.breaker import breaker_bus_hook
from mote.common.events.bus import EventBus
from mote.common.events.context import current_bus, observe_event, observe_event_sync, set_bus
from mote.common.events.journal import emit_journal_event
from mote.common.events.log_subscriber import LogSubscriber
from mote.common.events.outcomes import (
    CompactOutcome,
    PromptOutcome,
    SpawnOutcome,
    ToolCallOutcome,
    ToolResultOutcome,
    TurnOutcome,
)
from mote.common.events.scope import ScopePath, ScopeRef, current_scope, push_scope
from mote.common.events.stream import log_llm_stream
from mote.common.events.trace import current_span_id, span
from mote.common.events.types import (
    ACTIVITY_COMPLETED,
    ACTIVITY_STARTED,
    AGENT_LIFECYCLE,
    BREAKER_STATE_CHANGE,
    BUDGET,
    COMPACTION_CHECKPOINT,
    DIAGNOSTICS,
    FILE_CHANGED,
    FILE_MUTATED,
    FILE_SNAPSHOT,
    HISTORY_EDITED,
    HISTORY_RESET_EVENTS,
    JOURNAL,
    LLM_ERROR,
    LLM_REQUEST,
    LLM_RESPONSE,
    LLM_RETRY,
    LLM_STREAM_DELTA,
    LLM_STREAM_END,
    MESSAGE_APPENDED,
    OUTPUT_ACCEPTED,
    OUTPUT_CANDIDATE_RECEIVED,
    OUTPUT_COMMIT_STARTED,
    OUTPUT_COMMITTED,
    OUTPUT_PUBLISHED,
    OUTPUT_VALIDATION_REJECTED,
    POST_COMPACT,
    POST_TOOL_USE,
    PRE_AGENT_SPAWN,
    PRE_COMPACT,
    PRE_TOOL_USE,
    RECOVERY,
    RESOURCE_REPORT,
    RUN_LEASE,
    SESSION_END,
    SESSION_START,
    SPAN_END,
    SPAN_START,
    TASK_PROGRESS,
    TOOLS_CHANGED,
    TURN_END,
    TURN_START,
    USER_PROMPT_SUBMIT,
    ActivityCompletedEvent,
    ActivityStartedEvent,
    AgentEvent,
    AgentLifecycleEvent,
    BreakerStateChangeEvent,
    BudgetEvent,
    CompactionCheckpointEvent,
    DiagnosticsEvent,
    FileChangedEvent,
    FileMutatedEvent,
    FileSnapshotEvent,
    HistoryEditedEvent,
    JournalEvent,
    LLMErrorEvent,
    LLMRequestEvent,
    LLMResponseEvent,
    LLMRetryEvent,
    LLMStreamDeltaEvent,
    LLMStreamEndEvent,
    MessageAppendedEvent,
    OutputAcceptedEvent,
    OutputCandidateReceivedEvent,
    OutputCommitStartedEvent,
    OutputCommittedEvent,
    OutputMigratedEvent,
    OutputPublicationQueuedEvent,
    OutputPublishedEvent,
    OutputSnapshotEvent,
    OutputSnapshotInvalidatedEvent,
    OutputValidationRejectedEvent,
    PostCompactEvent,
    PostToolUseEvent,
    PreAgentSpawnEvent,
    PreCompactEvent,
    PreToolUseEvent,
    RecoveryEvent,
    ResourceReportEvent,
    Rewritable,
    Rewrite,
    RunLeaseEvent,
    SessionEndEvent,
    SessionStartEvent,
    SpanEndEvent,
    SpanStartEvent,
    TaskProgressEvent,
    ToolsChangedEvent,
    TurnEndEvent,
    TurnStartEvent,
    UserPromptSubmitEvent,
)

__all__ = [
    # bus + context
    "EventBus",
    "set_bus",
    "current_bus",
    "observe_event",
    "observe_event_sync",
    # activity scope spine
    "ScopeRef",
    "ScopePath",
    "current_scope",
    "push_scope",
    # llm stream
    "log_llm_stream",
    # trace instrumentation
    "span",
    "current_span_id",
    # subscribers
    "LogSubscriber",
    # typed control outcomes
    "ToolCallOutcome",
    "ToolResultOutcome",
    "PromptOutcome",
    "CompactOutcome",
    "SpawnOutcome",
    "TurnOutcome",
    # events
    "AgentEvent",
    "AgentLifecycleEvent",
    "ActivityStartedEvent",
    "ActivityCompletedEvent",
    "BudgetEvent",
    "SessionStartEvent",
    "SessionEndEvent",
    "TurnStartEvent",
    "TurnEndEvent",
    "MessageAppendedEvent",
    "OutputCandidateReceivedEvent",
    "OutputCommitStartedEvent",
    "OutputMigratedEvent",
    "OutputCommittedEvent",
    "OutputPublishedEvent",
    "OutputPublicationQueuedEvent",
    "OutputValidationRejectedEvent",
    "OutputAcceptedEvent",
    "LLMStreamDeltaEvent",
    "LLMStreamEndEvent",
    "OutputSnapshotEvent",
    "OutputSnapshotInvalidatedEvent",
    "RunLeaseEvent",
    "LLMRequestEvent",
    "LLMResponseEvent",
    "LLMErrorEvent",
    "LLMRetryEvent",
    "CompactionCheckpointEvent",
    "HistoryEditedEvent",
    "FileSnapshotEvent",
    "FileChangedEvent",
    "FileMutatedEvent",
    "ToolsChangedEvent",
    "DiagnosticsEvent",
    "RecoveryEvent",
    "BreakerStateChangeEvent",
    "breaker_bus_hook",
    "JournalEvent",
    "emit_journal_event",
    "TaskProgressEvent",
    "ResourceReportEvent",
    "SpanStartEvent",
    "SpanEndEvent",
    "UserPromptSubmitEvent",
    "PreToolUseEvent",
    "PostToolUseEvent",
    "PreCompactEvent",
    "PostCompactEvent",
    "PreAgentSpawnEvent",
    # rewrite provenance
    "Rewrite",
    "Rewritable",
    # discriminators
    "SESSION_START",
    "SESSION_END",
    "TURN_START",
    "TURN_END",
    "MESSAGE_APPENDED",
    "OUTPUT_CANDIDATE_RECEIVED",
    "OUTPUT_COMMIT_STARTED",
    "OUTPUT_COMMITTED",
    "OUTPUT_PUBLISHED",
    "OUTPUT_VALIDATION_REJECTED",
    "OUTPUT_ACCEPTED",
    "RUN_LEASE",
    "LLM_STREAM_DELTA",
    "LLM_STREAM_END",
    "LLM_REQUEST",
    "LLM_RESPONSE",
    "LLM_ERROR",
    "LLM_RETRY",
    "COMPACTION_CHECKPOINT",
    "HISTORY_EDITED",
    "HISTORY_RESET_EVENTS",
    "FILE_SNAPSHOT",
    "FILE_CHANGED",
    "FILE_MUTATED",
    "TOOLS_CHANGED",
    "DIAGNOSTICS",
    "RECOVERY",
    "BREAKER_STATE_CHANGE",
    "JOURNAL",
    "TASK_PROGRESS",
    "RESOURCE_REPORT",
    "AGENT_LIFECYCLE",
    "SPAN_START",
    "SPAN_END",
    "BUDGET",
    "ACTIVITY_STARTED",
    "ACTIVITY_COMPLETED",
    "USER_PROMPT_SUBMIT",
    "PRE_TOOL_USE",
    "POST_TOOL_USE",
    "PRE_COMPACT",
    "POST_COMPACT",
    "PRE_AGENT_SPAWN",
]
