"""Durable facts, bounded telemetry, scopes, and typed event contracts."""

from mote.contracts.events.agent import AGENT_LIFECYCLE, BUDGET, AgentLifecycleEvent, BudgetEvent
from mote.contracts.events.conversation import (
    CONTEXT_COMPACTED,
    HISTORY_EDITED,
    MESSAGE_APPENDED,
    MODEL_CONTEXT_REBUILT_EVENTS,
    POST_COMPACT,
    PROMPT_REJECTED,
    USER_PROMPT_SUBMIT,
    ContextCompactedEvent,
    HistoryEditedEvent,
    MessageAppendedEvent,
    PostCompactEvent,
    PromptRejectedEvent,
    UserPromptSubmitEvent,
)
from mote.contracts.events.file.observation import FILE_CHANGED, FILE_MUTATED, FileChangedEvent, FileMutatedEvent
from mote.contracts.events.model import (
    BREAKER_STATE_CHANGE,
    LLM_STREAM_COMMITTED,
    LLM_STREAM_DELTA,
    LLM_STREAM_DISCARDED,
    LLM_STREAM_END,
    LLM_STREAM_INTERRUPTED,
    MODEL_ATTEMPT_ADMISSION_REJECTED,
    MODEL_ATTEMPT_FINISHED,
    MODEL_ATTEMPT_STARTED,
    MODEL_CALL_FINISHED,
    MODEL_CALL_PLANNED,
    MODEL_FALLBACK_SELECTED,
    ROUTING_DECISION,
    BreakerStateChangeEvent,
    LLMStreamCommittedEvent,
    LLMStreamDeltaEvent,
    LLMStreamDiscardedEvent,
    LLMStreamEndEvent,
    LLMStreamInterruptedEvent,
    ModelAttemptAdmissionRejectedEvent,
    ModelAttemptFinishedEvent,
    ModelAttemptStartedEvent,
    ModelCallFinishedEvent,
    ModelCallPlannedEvent,
    ModelFallbackSelectedEvent,
    RoutingDecisionEvent,
)
from mote.contracts.events.output import (
    OUTPUT_ACCEPTED,
    OUTPUT_CANDIDATE_RECEIVED,
    OUTPUT_COMMIT_STARTED,
    OUTPUT_COMMITTED,
    OUTPUT_PUBLISHED,
    OUTPUT_VALIDATION_REJECTED,
    OutputAcceptedEvent,
    OutputCandidateReceivedEvent,
    OutputCommitStartedEvent,
    OutputCommittedEvent,
    OutputMigratedEvent,
    OutputPublicationQueuedEvent,
    OutputPublishedEvent,
    OutputSnapshotEvent,
    OutputSnapshotInvalidatedEvent,
    OutputValidationRejectedEvent,
)
from mote.contracts.events.session import (
    RUN_LEASE,
    SESSION_END,
    SESSION_START,
    TURN_END,
    TURN_START,
    RunLeaseEvent,
    SessionEndEvent,
    SessionStartEvent,
    TurnEndEvent,
    TurnStartEvent,
)
from mote.contracts.events.task import (
    ACTIVITY_COMPLETED,
    ACTIVITY_STARTED,
    TASK_PROGRESS,
    ActivityCompletedEvent,
    ActivityStartedEvent,
    TaskProgressEvent,
)
from mote.contracts.events.telemetry import (
    DIAGNOSTICS,
    JOURNAL,
    RECOVERY,
    RESOURCE_REPORT,
    SPAN_END,
    SPAN_START,
    DiagnosticsEvent,
    JournalEvent,
    RecoveryEvent,
    ResourceReportEvent,
    SpanEndEvent,
    SpanStartEvent,
)
from mote.contracts.events.tool import (
    TOOL_CALL_FINISHED,
    TOOL_INVOCATION_STARTED,
    TOOLS_CHANGED,
    ToolCallFinishedEvent,
    ToolInvocationStartedEvent,
    ToolsChangedEvent,
)
from mote.kernel.telemetry.events import current_span_id, span
from mote.runtime.events.breaker import breaker_telemetry_hook
from mote.runtime.events.context import bind_telemetry, current_telemetry, observe_event, observe_event_sync
from mote.runtime.events.dispatcher import SubscriptionBinding, SubscriptionManifest
from mote.runtime.events.fabric import EventFabric
from mote.runtime.events.journal import LocalEventJournal
from mote.runtime.events.log_subscriber import LogSubscriber
from mote.runtime.events.scope import ScopePath, ScopeRef, current_scope, push_scope
from mote.runtime.events.stream import log_llm_stream
from mote.runtime.events.telemetry import (
    TelemetryBinding,
    TelemetryHandle,
    TelemetryManifest,
    TelemetryRuntime,
    TelemetryState,
    TypedTelemetryBinding,
)

__all__ = [
    # fabric + telemetry context
    "EventFabric",
    "SubscriptionBinding",
    "SubscriptionManifest",
    "TelemetryBinding",
    "TelemetryHandle",
    "TelemetryManifest",
    "TelemetryRuntime",
    "TelemetryState",
    "TypedTelemetryBinding",
    "bind_telemetry",
    "current_telemetry",
    "observe_event",
    "observe_event_sync",
    # activity scope spine
    "ScopeRef",
    "ScopePath",
    "current_scope",
    "push_scope",
    # llm stream
    "log_llm_stream",
    # trace instrumentation
    "span",
    "current_span_id",
    # subscribers
    "LogSubscriber",
    "LocalEventJournal",
    # events
    "AgentLifecycleEvent",
    "ActivityStartedEvent",
    "ActivityCompletedEvent",
    "BudgetEvent",
    "SessionStartEvent",
    "SessionEndEvent",
    "TurnStartEvent",
    "TurnEndEvent",
    "MessageAppendedEvent",
    "OutputCandidateReceivedEvent",
    "OutputCommitStartedEvent",
    "OutputMigratedEvent",
    "OutputCommittedEvent",
    "OutputPublishedEvent",
    "OutputPublicationQueuedEvent",
    "OutputValidationRejectedEvent",
    "OutputAcceptedEvent",
    "LLMStreamDeltaEvent",
    "LLMStreamCommittedEvent",
    "LLMStreamDiscardedEvent",
    "LLMStreamInterruptedEvent",
    "LLMStreamEndEvent",
    "OutputSnapshotEvent",
    "OutputSnapshotInvalidatedEvent",
    "RunLeaseEvent",
    "ModelCallPlannedEvent",
    "ModelAttemptAdmissionRejectedEvent",
    "ModelAttemptStartedEvent",
    "ModelAttemptFinishedEvent",
    "ModelFallbackSelectedEvent",
    "ModelCallFinishedEvent",
    "ContextCompactedEvent",
    "HistoryEditedEvent",
    "FileChangedEvent",
    "FileMutatedEvent",
    "ToolsChangedEvent",
    "DiagnosticsEvent",
    "RecoveryEvent",
    "RoutingDecisionEvent",
    "BreakerStateChangeEvent",
    "breaker_telemetry_hook",
    "JournalEvent",
    "TaskProgressEvent",
    "ResourceReportEvent",
    "SpanStartEvent",
    "SpanEndEvent",
    "UserPromptSubmitEvent",
    "PromptRejectedEvent",
    "ToolInvocationStartedEvent",
    "ToolCallFinishedEvent",
    "PostCompactEvent",
    # discriminators
    "SESSION_START",
    "SESSION_END",
    "TURN_START",
    "TURN_END",
    "MESSAGE_APPENDED",
    "OUTPUT_CANDIDATE_RECEIVED",
    "OUTPUT_COMMIT_STARTED",
    "OUTPUT_COMMITTED",
    "OUTPUT_PUBLISHED",
    "OUTPUT_VALIDATION_REJECTED",
    "OUTPUT_ACCEPTED",
    "RUN_LEASE",
    "LLM_STREAM_DELTA",
    "LLM_STREAM_COMMITTED",
    "LLM_STREAM_DISCARDED",
    "LLM_STREAM_INTERRUPTED",
    "LLM_STREAM_END",
    "MODEL_CALL_PLANNED",
    "MODEL_ATTEMPT_ADMISSION_REJECTED",
    "MODEL_ATTEMPT_STARTED",
    "MODEL_ATTEMPT_FINISHED",
    "MODEL_FALLBACK_SELECTED",
    "MODEL_CALL_FINISHED",
    "CONTEXT_COMPACTED",
    "HISTORY_EDITED",
    "MODEL_CONTEXT_REBUILT_EVENTS",
    "FILE_CHANGED",
    "FILE_MUTATED",
    "TOOLS_CHANGED",
    "DIAGNOSTICS",
    "RECOVERY",
    "ROUTING_DECISION",
    "BREAKER_STATE_CHANGE",
    "JOURNAL",
    "TASK_PROGRESS",
    "RESOURCE_REPORT",
    "AGENT_LIFECYCLE",
    "SPAN_START",
    "SPAN_END",
    "BUDGET",
    "ACTIVITY_STARTED",
    "ACTIVITY_COMPLETED",
    "USER_PROMPT_SUBMIT",
    "PROMPT_REJECTED",
    "TOOL_INVOCATION_STARTED",
    "TOOL_CALL_FINISHED",
    "POST_COMPACT",
]
