# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from mote.product.inference.daemon.rpc import gateway_v1_pb2 as gateway__v1__pb2


class GatewayExecutionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartUnary = channel.unary_unary(
                '/mote.inference.gateway.v1.GatewayExecutionService/StartUnary',
                request_serializer=gateway__v1__pb2.StartRequest.SerializeToString,
                response_deserializer=gateway__v1__pb2.StartResponse.FromString,
                )
        self.StartDurableCommand = channel.unary_unary(
                '/mote.inference.gateway.v1.GatewayExecutionService/StartDurableCommand',
                request_serializer=gateway__v1__pb2.StartRequest.SerializeToString,
                response_deserializer=gateway__v1__pb2.StartResponse.FromString,
                )
        self.OpenSession = channel.unary_unary(
                '/mote.inference.gateway.v1.GatewayExecutionService/OpenSession',
                request_serializer=gateway__v1__pb2.StartRequest.SerializeToString,
                response_deserializer=gateway__v1__pb2.StartResponse.FromString,
                )
        self.ExecuteTransferPart = channel.unary_unary(
                '/mote.inference.gateway.v1.GatewayExecutionService/ExecuteTransferPart',
                request_serializer=gateway__v1__pb2.TransferPartRequest.SerializeToString,
                response_deserializer=gateway__v1__pb2.StartResponse.FromString,
                )
        self.AuthorizeWire = channel.unary_unary(
                '/mote.inference.gateway.v1.GatewayExecutionService/AuthorizeWire',
                request_serializer=gateway__v1__pb2.AuthorizeRequest.SerializeToString,
                response_deserializer=gateway__v1__pb2.Empty.FromString,
                )
        self.Cancel = channel.unary_unary(
                '/mote.inference.gateway.v1.GatewayExecutionService/Cancel',
                request_serializer=gateway__v1__pb2.CancelRequest.SerializeToString,
                response_deserializer=gateway__v1__pb2.Empty.FromString,
                )
        self.StreamEvents = channel.unary_stream(
                '/mote.inference.gateway.v1.GatewayExecutionService/StreamEvents',
                request_serializer=gateway__v1__pb2.CursorRequest.SerializeToString,
                response_deserializer=gateway__v1__pb2.LifecycleEvent.FromString,
                )
        self.Session = channel.stream_stream(
                '/mote.inference.gateway.v1.GatewayExecutionService/Session',
                request_serializer=gateway__v1__pb2.SessionMessage.SerializeToString,
                response_deserializer=gateway__v1__pb2.LifecycleEvent.FromString,
                )
        self.QueryReceipt = channel.unary_unary(
                '/mote.inference.gateway.v1.GatewayExecutionService/QueryReceipt',
                request_serializer=gateway__v1__pb2.ReceiptRequest.SerializeToString,
                response_deserializer=gateway__v1__pb2.Receipt.FromString,
                )
        self.Reconcile = channel.unary_stream(
                '/mote.inference.gateway.v1.GatewayExecutionService/Reconcile',
                request_serializer=gateway__v1__pb2.ReceiptRequest.SerializeToString,
                response_deserializer=gateway__v1__pb2.LifecycleEvent.FromString,
                )


class GatewayExecutionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartUnary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartDurableCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteTransferPart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AuthorizeWire(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Session(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryReceipt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reconcile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewayExecutionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartUnary': grpc.unary_unary_rpc_method_handler(
                    servicer.StartUnary,
                    request_deserializer=gateway__v1__pb2.StartRequest.FromString,
                    response_serializer=gateway__v1__pb2.StartResponse.SerializeToString,
            ),
            'StartDurableCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.StartDurableCommand,
                    request_deserializer=gateway__v1__pb2.StartRequest.FromString,
                    response_serializer=gateway__v1__pb2.StartResponse.SerializeToString,
            ),
            'OpenSession': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenSession,
                    request_deserializer=gateway__v1__pb2.StartRequest.FromString,
                    response_serializer=gateway__v1__pb2.StartResponse.SerializeToString,
            ),
            'ExecuteTransferPart': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTransferPart,
                    request_deserializer=gateway__v1__pb2.TransferPartRequest.FromString,
                    response_serializer=gateway__v1__pb2.StartResponse.SerializeToString,
            ),
            'AuthorizeWire': grpc.unary_unary_rpc_method_handler(
                    servicer.AuthorizeWire,
                    request_deserializer=gateway__v1__pb2.AuthorizeRequest.FromString,
                    response_serializer=gateway__v1__pb2.Empty.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=gateway__v1__pb2.CancelRequest.FromString,
                    response_serializer=gateway__v1__pb2.Empty.SerializeToString,
            ),
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=gateway__v1__pb2.CursorRequest.FromString,
                    response_serializer=gateway__v1__pb2.LifecycleEvent.SerializeToString,
            ),
            'Session': grpc.stream_stream_rpc_method_handler(
                    servicer.Session,
                    request_deserializer=gateway__v1__pb2.SessionMessage.FromString,
                    response_serializer=gateway__v1__pb2.LifecycleEvent.SerializeToString,
            ),
            'QueryReceipt': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryReceipt,
                    request_deserializer=gateway__v1__pb2.ReceiptRequest.FromString,
                    response_serializer=gateway__v1__pb2.Receipt.SerializeToString,
            ),
            'Reconcile': grpc.unary_stream_rpc_method_handler(
                    servicer.Reconcile,
                    request_deserializer=gateway__v1__pb2.ReceiptRequest.FromString,
                    response_serializer=gateway__v1__pb2.LifecycleEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mote.inference.gateway.v1.GatewayExecutionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GatewayExecutionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartUnary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mote.inference.gateway.v1.GatewayExecutionService/StartUnary',
            gateway__v1__pb2.StartRequest.SerializeToString,
            gateway__v1__pb2.StartResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartDurableCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mote.inference.gateway.v1.GatewayExecutionService/StartDurableCommand',
            gateway__v1__pb2.StartRequest.SerializeToString,
            gateway__v1__pb2.StartResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OpenSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mote.inference.gateway.v1.GatewayExecutionService/OpenSession',
            gateway__v1__pb2.StartRequest.SerializeToString,
            gateway__v1__pb2.StartResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExecuteTransferPart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mote.inference.gateway.v1.GatewayExecutionService/ExecuteTransferPart',
            gateway__v1__pb2.TransferPartRequest.SerializeToString,
            gateway__v1__pb2.StartResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AuthorizeWire(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mote.inference.gateway.v1.GatewayExecutionService/AuthorizeWire',
            gateway__v1__pb2.AuthorizeRequest.SerializeToString,
            gateway__v1__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mote.inference.gateway.v1.GatewayExecutionService/Cancel',
            gateway__v1__pb2.CancelRequest.SerializeToString,
            gateway__v1__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/mote.inference.gateway.v1.GatewayExecutionService/StreamEvents',
            gateway__v1__pb2.CursorRequest.SerializeToString,
            gateway__v1__pb2.LifecycleEvent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Session(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/mote.inference.gateway.v1.GatewayExecutionService/Session',
            gateway__v1__pb2.SessionMessage.SerializeToString,
            gateway__v1__pb2.LifecycleEvent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryReceipt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mote.inference.gateway.v1.GatewayExecutionService/QueryReceipt',
            gateway__v1__pb2.ReceiptRequest.SerializeToString,
            gateway__v1__pb2.Receipt.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Reconcile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/mote.inference.gateway.v1.GatewayExecutionService/Reconcile',
            gateway__v1__pb2.ReceiptRequest.SerializeToString,
            gateway__v1__pb2.LifecycleEvent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class GatewayControlServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Authenticate = channel.unary_unary(
                '/mote.inference.gateway.v1.GatewayControlService/Authenticate',
                request_serializer=gateway__v1__pb2.HandshakeRequest.SerializeToString,
                response_deserializer=gateway__v1__pb2.HandshakeResponse.FromString,
                )
        self.Negotiate = channel.unary_unary(
                '/mote.inference.gateway.v1.GatewayControlService/Negotiate',
                request_serializer=gateway__v1__pb2.NegotiationRequest.SerializeToString,
                response_deserializer=gateway__v1__pb2.NegotiationResponse.FromString,
                )
        self.StageGeneration = channel.unary_unary(
                '/mote.inference.gateway.v1.GatewayControlService/StageGeneration',
                request_serializer=gateway__v1__pb2.GenerationRequest.SerializeToString,
                response_deserializer=gateway__v1__pb2.GenerationStatus.FromString,
                )
        self.ObserveGeneration = channel.unary_unary(
                '/mote.inference.gateway.v1.GatewayControlService/ObserveGeneration',
                request_serializer=gateway__v1__pb2.GenerationRequest.SerializeToString,
                response_deserializer=gateway__v1__pb2.GenerationStatus.FromString,
                )
        self.GetReadiness = channel.unary_unary(
                '/mote.inference.gateway.v1.GatewayControlService/GetReadiness',
                request_serializer=gateway__v1__pb2.Empty.SerializeToString,
                response_deserializer=gateway__v1__pb2.Readiness.FromString,
                )
        self.Backup = channel.unary_unary(
                '/mote.inference.gateway.v1.GatewayControlService/Backup',
                request_serializer=gateway__v1__pb2.BackupRequest.SerializeToString,
                response_deserializer=gateway__v1__pb2.BackupResult.FromString,
                )
        self.VerifyRestore = channel.unary_unary(
                '/mote.inference.gateway.v1.GatewayControlService/VerifyRestore',
                request_serializer=gateway__v1__pb2.VerifyRestoreRequest.SerializeToString,
                response_deserializer=gateway__v1__pb2.VerifyRestoreResult.FromString,
                )
        self.ReconcileAll = channel.unary_unary(
                '/mote.inference.gateway.v1.GatewayControlService/ReconcileAll',
                request_serializer=gateway__v1__pb2.ReconcileAllRequest.SerializeToString,
                response_deserializer=gateway__v1__pb2.ReconcileAllResult.FromString,
                )
        self.BeginDrain = channel.unary_unary(
                '/mote.inference.gateway.v1.GatewayControlService/BeginDrain',
                request_serializer=gateway__v1__pb2.DrainRequest.SerializeToString,
                response_deserializer=gateway__v1__pb2.Readiness.FromString,
                )


class GatewayControlServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Authenticate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Negotiate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StageGeneration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObserveGeneration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReadiness(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Backup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyRestore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReconcileAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginDrain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewayControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Authenticate': grpc.unary_unary_rpc_method_handler(
                    servicer.Authenticate,
                    request_deserializer=gateway__v1__pb2.HandshakeRequest.FromString,
                    response_serializer=gateway__v1__pb2.HandshakeResponse.SerializeToString,
            ),
            'Negotiate': grpc.unary_unary_rpc_method_handler(
                    servicer.Negotiate,
                    request_deserializer=gateway__v1__pb2.NegotiationRequest.FromString,
                    response_serializer=gateway__v1__pb2.NegotiationResponse.SerializeToString,
            ),
            'StageGeneration': grpc.unary_unary_rpc_method_handler(
                    servicer.StageGeneration,
                    request_deserializer=gateway__v1__pb2.GenerationRequest.FromString,
                    response_serializer=gateway__v1__pb2.GenerationStatus.SerializeToString,
            ),
            'ObserveGeneration': grpc.unary_unary_rpc_method_handler(
                    servicer.ObserveGeneration,
                    request_deserializer=gateway__v1__pb2.GenerationRequest.FromString,
                    response_serializer=gateway__v1__pb2.GenerationStatus.SerializeToString,
            ),
            'GetReadiness': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReadiness,
                    request_deserializer=gateway__v1__pb2.Empty.FromString,
                    response_serializer=gateway__v1__pb2.Readiness.SerializeToString,
            ),
            'Backup': grpc.unary_unary_rpc_method_handler(
                    servicer.Backup,
                    request_deserializer=gateway__v1__pb2.BackupRequest.FromString,
                    response_serializer=gateway__v1__pb2.BackupResult.SerializeToString,
            ),
            'VerifyRestore': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyRestore,
                    request_deserializer=gateway__v1__pb2.VerifyRestoreRequest.FromString,
                    response_serializer=gateway__v1__pb2.VerifyRestoreResult.SerializeToString,
            ),
            'ReconcileAll': grpc.unary_unary_rpc_method_handler(
                    servicer.ReconcileAll,
                    request_deserializer=gateway__v1__pb2.ReconcileAllRequest.FromString,
                    response_serializer=gateway__v1__pb2.ReconcileAllResult.SerializeToString,
            ),
            'BeginDrain': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginDrain,
                    request_deserializer=gateway__v1__pb2.DrainRequest.FromString,
                    response_serializer=gateway__v1__pb2.Readiness.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mote.inference.gateway.v1.GatewayControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GatewayControlService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Authenticate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mote.inference.gateway.v1.GatewayControlService/Authenticate',
            gateway__v1__pb2.HandshakeRequest.SerializeToString,
            gateway__v1__pb2.HandshakeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Negotiate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mote.inference.gateway.v1.GatewayControlService/Negotiate',
            gateway__v1__pb2.NegotiationRequest.SerializeToString,
            gateway__v1__pb2.NegotiationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StageGeneration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mote.inference.gateway.v1.GatewayControlService/StageGeneration',
            gateway__v1__pb2.GenerationRequest.SerializeToString,
            gateway__v1__pb2.GenerationStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ObserveGeneration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mote.inference.gateway.v1.GatewayControlService/ObserveGeneration',
            gateway__v1__pb2.GenerationRequest.SerializeToString,
            gateway__v1__pb2.GenerationStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetReadiness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mote.inference.gateway.v1.GatewayControlService/GetReadiness',
            gateway__v1__pb2.Empty.SerializeToString,
            gateway__v1__pb2.Readiness.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Backup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mote.inference.gateway.v1.GatewayControlService/Backup',
            gateway__v1__pb2.BackupRequest.SerializeToString,
            gateway__v1__pb2.BackupResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VerifyRestore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mote.inference.gateway.v1.GatewayControlService/VerifyRestore',
            gateway__v1__pb2.VerifyRestoreRequest.SerializeToString,
            gateway__v1__pb2.VerifyRestoreResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReconcileAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mote.inference.gateway.v1.GatewayControlService/ReconcileAll',
            gateway__v1__pb2.ReconcileAllRequest.SerializeToString,
            gateway__v1__pb2.ReconcileAllResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BeginDrain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mote.inference.gateway.v1.GatewayControlService/BeginDrain',
            gateway__v1__pb2.DrainRequest.SerializeToString,
            gateway__v1__pb2.Readiness.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
