"""Bash command tool — aligned with Codex's shell model (stable cwd, no drift).

Runs a shell command against a *stable* working directory. The cwd is treated as
a fixed data value (the session's ``working_dir``, defaulting to the startup
dir); it is NOT mutated by the command. A bare ``cd`` inside a command does not
persist to the next call — to operate in a subdirectory, pass the per-call
``workdir`` parameter instead.

aexecute() spawns a fresh subprocess per call (no persistent shell), so a bare
`cd` would not survive across calls regardless; we deliberately do not emulate
persistence. This mirrors Codex: cwd is passed in explicitly on every spawn, the
process cwd is never read, and directory scoping is a per-call ``workdir`` arg.

Cwd ownership stays in the Role. This tool only borrows two narrow accessors
(get_cwd for the stable base dir, get_sandbox_runtime) injected by bind(); it
never sees RoleState or memory, and it never writes cwd back.
"""
from __future__ import annotations

import json
import os
from typing import Any, ClassVar, cast

from mote.contracts.authorization import PermissionDecision
from mote.runtime.errors import ToolError
from mote.runtime.process import aexecute
from mote.runtime.tools.base_tool import BaseTool
from mote.runtime.tools.capability_types import GetCwd, GetSandboxRuntime
from mote.runtime.tools.permission.classifier import classify_command
from mote.runtime.tools.permission.command_parse import segment_strings
from mote.runtime.tools.tool_registry import register_tool
from mote.runtime.tools.tool_result import ToolResult

# Complete model-facing message sentences, hoisted to module-top templates so the
# wording lives in one place (fill via ``.format(...)`` at the raise site).
_MSG_COMMAND_REQUIRED = "Error: 'command' argument is required."
_MSG_WORKDIR_NOT_EXIST = "Error: workdir does not exist: {workdir}"
_MSG_EXEC_FAILED = "Error executing command: {error}"
# When ``check`` is on, a non-zero exit turns the whole call into a failure so a
# graph node isolates it (rather than reading the error text as a normal value).
_MSG_CHECK_FAILED = "Command failed with exit code {rc}."

# The env var carrying the whole ``inputs`` object as JSON.
_INPUTS_ENV = "INPUTS"


def _inputs_to_env(inputs: dict) -> dict[str, str]:
    """Project ``inputs`` into shell env vars.

    The whole object is JSON-encoded under ``$INPUTS`` (so nested/complex values
    are always reachable); on top of that, every scalar entry with an
    identifier-safe key is also exported as its own env var for direct shell use
    (``$name``). Scalars are stringified shell-idiomatically — a bool becomes
    ``true``/``false``, numbers their decimal form, a string verbatim. Non-scalar
    entries (dict/list/None) are reachable only via ``$INPUTS``.
    """
    env: dict[str, str] = {_INPUTS_ENV: json.dumps(inputs, default=str)}
    for key, value in inputs.items():
        if not (isinstance(key, str) and key.isidentifier()) or key == _INPUTS_ENV:
            continue
        if isinstance(value, bool):
            env[key] = "true" if value else "false"
        elif isinstance(value, str):
            env[key] = value
        elif isinstance(value, (int, float)):
            env[key] = str(value)
        # dict / list / None: only via $INPUTS.
    return env


def _structured(stdout: str) -> Any:
    """The structured result for a caller: parsed JSON if stdout is JSON, else text.

    Lets a graph ``$ref`` index into a command that emits JSON, while a plain
    text command still yields its (clean) stdout string. Empty stdout -> None.
    """
    clean = stdout.rstrip("\n") if stdout else ""
    if not clean:
        return None
    try:
        return json.loads(clean)
    except (ValueError, TypeError):
        return clean


@register_tool
class Bash(BaseTool):
    """Run a bash command against the stable working directory and return its output."""

    name = "Bash"
    aliases = ["Bash.run", "bash"]
    # Command output is treated as re-derivable (the command can be re-run); its
    # folded body can be cleared and, if still needed, regenerated by re-invoking.
    reconstructable: ClassVar[bool] = True
    # Shell output can be verbose; cap below the default.
    max_result_size_chars: ClassVar[int] = 30_000
    requires = ("get_cwd", "get_sandbox_runtime")
    # Arbitrary command execution — the highest-risk tool.
    risk_level = "high"

    # Injected from Role by bind() — the stable-cwd accessor plus the optional
    # OS-level sandbox runtime accessor, never RoleState or memory.
    get_cwd: GetCwd
    # Capability accessor returning the session's SandboxRuntime, or None when
    # no OS-level sandbox is configured. Defaults to a no-runtime stub so a
    # tool bound without a Role (some unit tests) still runs un-sandboxed.
    get_sandbox_runtime: GetSandboxRuntime = staticmethod(lambda: None)

    def permission_target(self, args: dict) -> str:
        """The command string — matched against ``Bash(pattern)`` rules."""
        return args.get("command") or ""

    def permission_segments(self, args: dict) -> "list[str] | None":
        """Split the command on shell operators for per-segment rule matching."""
        command = args.get("command") or ""
        return segment_strings(command) or None

    def check_permissions(self, args: dict) -> "PermissionDecision | None":
        """Classify the command and short-circuit the obvious cases.

        Uses the shared :func:`classify_command` (Codex-style safety pre-check):

          * destructive (``rm -rf``, ``mkfs``, ``sudo`` ...) -> ``ask``
            (bypass-immune — forces a prompt regardless of allow rules / mode);
          * verifiably read-only (``ls``, ``cat``, ``git status`` ...) ->
            ``allow`` (auto-approved, no prompt in ``default`` mode);
          * anything unrecognised -> ``None`` to defer to rules/mode.
        """
        command = args.get("command") or ""
        assessment = classify_command(command)
        if assessment.risk == "high":
            return PermissionDecision.ask(
                "tool_check",
                "potentially destructive command",
                message=f"This command looks destructive: {command}",
            )
        if assessment.known_safe:
            return PermissionDecision.allow("tool_check", assessment.reason)
        return None

    async def call(
        self,
        *,
        command: str,
        inputs: dict[str, Any] | None = None,
        timeout: float = 300.0,
        workdir: str = "",
        check: bool = False,
    ) -> ToolResult:
        """Run a one-shot shell command — also fetches web pages via curl/wget.

        Runs against the session's stable working directory; use ``workdir`` to
        run in a subdirectory, since a ``cd`` does not persist across calls.

        By default a non-zero exit is NOT an error — it is annotated in the output
        and the call still succeeds (``grep`` with no match, ``diff`` that finds
        changes, etc. exit non-zero legitimately). Pass ``check=True`` when the
        command MUST succeed, so a ``run_graph`` map/fold node isolates a failure
        via ``on_item_error`` rather than reading the error text as a value.

        To fetch a web page, run ``curl <url>`` (or ``wget -qO- <url>``): HTML is
        auto-cleaned into readable Markdown. Use the WebBrowser tool instead when
        you must interact (click/type/log in) or the page is JS-rendered.

        Args:
            command: The bash command to execute.
            inputs: Optional object of typed values fed to the command: the whole
                object as ``$INPUTS`` (JSON) and each identifier-safe scalar as its
                own ``$name`` env var — how a graph node passes upstream values.
                Native-channel only (structured param); omit under the XML protocol.
            timeout: Max seconds to wait (default 300). On timeout the command is
                terminated and the output so far is returned (not raised).
            workdir: Optional directory to run this one command in (relative to the
                session cwd). Use it to scope to a subdirectory — a ``cd`` inside
                the command does NOT persist across calls.
            check: When True, a non-zero exit fails the call (``success=False``)
                instead of annotating it — surfaces a failure that would otherwise
                pass silently (e.g. an isolated ``run_graph`` map item). Leave False
                when a non-zero exit is expected (``grep`` no-hit, ``diff``). A
                timeout is unaffected by ``check``.

        Returns:
            A ``ToolResult`` whose ``output`` is the stdout/stderr/exit-code text
            and whose ``data`` is structured: stdout parsed as JSON when valid,
            else the raw stdout string, so a downstream graph ``$ref`` can index
            it. With ``check=True`` a non-zero exit yields ``success=False``
            (``error`` set), leaving ``data`` unset.
        """
        if not command or not command.strip():
            raise ToolError(_MSG_COMMAND_REQUIRED)

        cwd = self.get_cwd()
        base_cwd = cwd if cwd and os.path.isdir(cwd) else None

        # `workdir` scopes this one command to a directory (relative paths
        # resolve against the stable base cwd). Without it we run in the stable
        # base cwd. Either way the session's cwd is never mutated — a `cd` inside
        # the command does not persist (Codex-aligned: cwd is data, not state).
        if workdir:
            run_cwd = workdir if os.path.isabs(workdir) else os.path.join(base_cwd or os.getcwd(), workdir)
            if not os.path.isdir(run_cwd):
                raise ToolError(_MSG_WORKDIR_NOT_EXIST.format(workdir=workdir))
        else:
            run_cwd = base_cwd  # may be None -> aexecute uses the process default

        # OS-level sandbox: when a runtime is wired, aexecute wraps the command
        # (bwrap + hardening) and amends the env before spawning. None => the
        # historical un-sandboxed path.
        runtime = self.get_sandbox_runtime() if self.get_sandbox_runtime is not None else None

        # inputs -> env: only build a full env (process env + injected vars) when
        # inputs are given; otherwise pass None so the subprocess inherits the
        # parent env exactly as before (no behavioural change for plain calls).
        env = {**os.environ, **_inputs_to_env(inputs)} if inputs else None

        try:
            # return_partial_on_timeout=True always yields the 4-tuple
            # (rc, stdout, stderr, timed_out); narrow the declared union.
            rc, stdout, stderr, timed_out = cast(
                "tuple[int, str, str, bool]",
                await aexecute(
                    command,
                    working_dir=run_cwd,
                    env=env,
                    wait=True,
                    timeout=timeout,
                    return_partial_on_timeout=True,
                    sandbox_runtime=runtime,
                ),
            )
        except Exception as e:
            raise ToolError(_MSG_EXEC_FAILED.format(error=e))

        output = stdout.rstrip("\n") if stdout else ""
        parts = []
        if timed_out:
            parts.append(f"command timed out after {int(timeout * 1000)} milliseconds")
        if output:
            parts.append(output)
        if stderr:
            parts.append(stderr)
        if not timed_out and rc:
            parts.append(f"[exit code: {rc}]")
        text = "\n".join(parts) if parts else ""

        # ``check``: a non-zero exit (that is NOT a timeout — a timeout carries its
        # own message and is not a normal exit code) fails the call, so a caller
        # like a run_graph map/fold node isolates it via on_item_error instead of
        # reading the error text as a normal value. The reason line leads, followed
        # by the command's own output (stdout/stderr) so the model can see what went
        # wrong; ``data`` is left unset because a failed command has no trustworthy
        # structured result. (``error`` is an ErrorReport, not a string — a plain
        # failure carries its reason in ``output``, which ``_unwrap`` reads back.)
        if check and rc and not timed_out:
            reason = _MSG_CHECK_FAILED.format(rc=rc)
            return ToolResult(output=f"{reason}\n{text}" if text else reason, success=False)
        return ToolResult(output=text, data=_structured(stdout))

    def cleanup_session(self, session_id: str) -> None:
        """No persistent process to tear down; aexecute spawns per-call."""
