#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""``mote.cli.contracts.view`` — the shared human-protocol contract.

The ``ViewEvent`` tagged union (:mod:`~mote.cli.contracts.view.events`) plus the
declarative capability bits + per-consumer downgrade adapter
(:mod:`~mote.cli.contracts.view.capabilities`). These are the *cross-host*
contracts — every host that renders for a person shares them — so they sit in
the shared ``contracts`` layer, while the concrete ``AgentEvent → ViewEvent`` fold
(``ViewProjector``) stays host-side in :mod:`mote.cli.view`.
"""

from mote.cli.contracts.view.capabilities import STRUCTURED_CAPS, TERMINAL_CAPS, Capabilities, CapabilityAdapter
from mote.cli.contracts.view.events import (
    ACTIVITY_COMPLETED,
    ACTIVITY_STARTED,
    APPROVAL_REQUESTED,
    CONVERSATION_COMPACTED,
    ERROR_RAISED,
    FILE_DIFF_BLOCK,
    MEDIA_BLOCK,
    MESSAGE_BLOCK_COMPLETED,
    MESSAGE_BLOCK_DELTA,
    MESSAGE_BLOCK_STARTED,
    NOTICE,
    QUESTION_ASKED,
    REASONING_DELTA,
    RESULT_KIND_DIFF,
    RESULT_KIND_MEDIA,
    RESULT_KIND_PLAIN,
    RESULT_KIND_TABLE,
    RETRY_STATUS,
    SESSION_LIST_SHOWN,
    SYSTEM_REMINDER,
    TASK_PROGRESS,
    TOOL_CALL_COMPLETED,
    TOOL_CALL_STARTED,
    TRANSCRIPT_CLEARED,
    USAGE_UPDATED,
    ActivityCompleted,
    ActivityStarted,
    ApprovalDecision,
    ApprovalRequested,
    ConversationCompacted,
    ErrorRaised,
    FileDiffBlock,
    MediaBlock,
    MessageBlockCompleted,
    MessageBlockDelta,
    MessageBlockStarted,
    Notice,
    QuestionAsked,
    ReasoningDelta,
    RetryStatus,
    SessionListItem,
    SessionListShown,
    SystemReminder,
    TaskProgress,
    ToolCallCompleted,
    ToolCallStarted,
    TranscriptCleared,
    UsageUpdated,
    ViewEvent,
)

__all__ = [
    "ViewEvent",
    "MessageBlockStarted",
    "MessageBlockDelta",
    "MessageBlockCompleted",
    "ReasoningDelta",
    "ToolCallStarted",
    "ToolCallCompleted",
    "MediaBlock",
    "FileDiffBlock",
    "TaskProgress",
    "Notice",
    "ErrorRaised",
    "QuestionAsked",
    "ApprovalRequested",
    "ApprovalDecision",
    "UsageUpdated",
    "SessionListItem",
    "SessionListShown",
    "RetryStatus",
    "TranscriptCleared",
    "SystemReminder",
    "ConversationCompacted",
    "ActivityStarted",
    "ActivityCompleted",
    "MESSAGE_BLOCK_STARTED",
    "MESSAGE_BLOCK_DELTA",
    "MESSAGE_BLOCK_COMPLETED",
    "REASONING_DELTA",
    "TOOL_CALL_STARTED",
    "TOOL_CALL_COMPLETED",
    "MEDIA_BLOCK",
    "FILE_DIFF_BLOCK",
    "TASK_PROGRESS",
    "NOTICE",
    "ERROR_RAISED",
    "QUESTION_ASKED",
    "APPROVAL_REQUESTED",
    "USAGE_UPDATED",
    "SESSION_LIST_SHOWN",
    "RETRY_STATUS",
    "TRANSCRIPT_CLEARED",
    "SYSTEM_REMINDER",
    "CONVERSATION_COMPACTED",
    "ACTIVITY_STARTED",
    "ACTIVITY_COMPLETED",
    "RESULT_KIND_PLAIN",
    "RESULT_KIND_DIFF",
    "RESULT_KIND_TABLE",
    "RESULT_KIND_MEDIA",
    "Capabilities",
    "CapabilityAdapter",
    "TERMINAL_CAPS",
    "STRUCTURED_CAPS",
]
