"""Stable Agent identity, catalog, spawn, and lifecycle contracts."""

from mote.contracts.agent.activation import ApprovedDeclaration, ApprovedSourceIdentity
from mote.contracts.agent.cancellation import (
    AgentCancellationCommand,
    AgentCancellationDisposition,
    AgentCancellationPort,
    AgentCancellationReceipt,
    SubtreeCancellationReceipt,
)
from mote.contracts.agent.capacity import (
    CapacityReservationDisposition,
    CapacitySettlementDisposition,
    LogicalCapacityLimit,
    LogicalCapacityReservationReceipt,
    LogicalCapacityScope,
    LogicalCapacityScopeKind,
    LogicalCapacitySettlementReceipt,
    ResidentCapacityReservationReceipt,
    ResidentCapacitySettlementReceipt,
    TurnCapacityPermitReceipt,
    TurnCapacitySettlementReceipt,
)
from mote.contracts.agent.identity import AgentDescriptor, BaseAgent
from mote.contracts.agent.lineage import (
    LineageAuthorizationDisposition,
    LineageAuthorizationReceipt,
    LineageRecord,
    SpawnAdvanceDisposition,
    SpawnAdvanceReceipt,
    SpawnLifecycle,
    SpawnRequest,
    SubtreeLineageSnapshot,
)
from mote.contracts.agent.runtime_identity import AgentId
from mote.contracts.agent.spawn import (
    AgentBuilder,
    AgentConstructionRequest,
    ContextPolicy,
    CostAttributionPort,
    Lifecycle,
    RunnableAgent,
    SpawnableAgentDefinition,
    SpawnContext,
    SpawnPlan,
)

__all__ = [
    "ApprovedDeclaration",
    "ApprovedSourceIdentity",
    "CapacityReservationDisposition",
    "CapacitySettlementDisposition",
    "AgentBuilder",
    "AgentCancellationCommand",
    "AgentCancellationDisposition",
    "AgentCancellationPort",
    "AgentCancellationReceipt",
    "AgentConstructionRequest",
    "CostAttributionPort",
    "AgentDescriptor",
    "AgentId",
    "BaseAgent",
    "ContextPolicy",
    "Lifecycle",
    "LineageRecord",
    "LineageAuthorizationDisposition",
    "LineageAuthorizationReceipt",
    "LogicalCapacityLimit",
    "LogicalCapacityReservationReceipt",
    "LogicalCapacityScope",
    "LogicalCapacityScopeKind",
    "LogicalCapacitySettlementReceipt",
    "RunnableAgent",
    "ResidentCapacityReservationReceipt",
    "ResidentCapacitySettlementReceipt",
    "SpawnContext",
    "SpawnAdvanceDisposition",
    "SpawnAdvanceReceipt",
    "SpawnLifecycle",
    "SpawnPlan",
    "SpawnRequest",
    "SpawnableAgentDefinition",
    "SubtreeLineageSnapshot",
    "SubtreeCancellationReceipt",
    "TurnCapacityPermitReceipt",
    "TurnCapacitySettlementReceipt",
]
