"""Bash command tool — aligned with Codex's shell model (stable cwd, no drift).

Runs a shell command against a *stable* working directory. The cwd is treated as
a fixed data value (the session's ``working_dir``, defaulting to the startup
dir); it is NOT mutated by the command. A bare ``cd`` inside a command does not
persist to the next call — to operate in a subdirectory, pass the per-call
``workdir`` parameter instead.

aexecute() spawns a fresh subprocess per call (no persistent shell), so a bare
`cd` would not survive across calls regardless; we deliberately do not emulate
persistence. This mirrors Codex: cwd is passed in explicitly on every spawn, the
process cwd is never read, and directory scoping is a per-call ``workdir`` arg.

Cwd ownership stays in the Role. This tool only borrows two narrow accessors
(get_cwd for the stable base dir, get_sandbox_runtime) injected by bind(); it
never sees RoleState or memory, and it never writes cwd back.
"""
from __future__ import annotations

import os
from typing import Callable, ClassVar, cast

from mote.common.prompt.tools import BASH_DESCRIPTION
from mote.common.schema.permission_types import PermissionDecision
from mote.common.utils.common import aexecute
from mote.executor.base_tool import BaseTool
from mote.executor.permission.classifier import classify_command
from mote.executor.permission.command_parse import segment_strings
from mote.executor.tool_registry import register_tool
from mote.executor.tool_result import ToolError

# Complete model-facing message sentences, hoisted to module-top templates so the
# wording lives in one place (fill via ``.format(...)`` at the raise site).
_MSG_COMMAND_REQUIRED = "Error: 'command' argument is required."
_MSG_WORKDIR_NOT_EXIST = "Error: workdir does not exist: {workdir}"
_MSG_EXEC_FAILED = "Error executing command: {error}"


@register_tool
class Bash(BaseTool):
    """Run a bash command against the stable working directory and return its output."""

    name = "Bash"
    aliases = ["Bash.run", "bash"]
    # Command output is treated as re-derivable (the command can be re-run); its
    # folded body can be cleared and, if still needed, regenerated by re-invoking.
    reconstructable: ClassVar[bool] = True
    # Shell output can be verbose; cap below the default.
    max_result_size_chars: ClassVar[int] = 30_000
    description = BASH_DESCRIPTION
    requires = ("get_cwd", "get_sandbox_runtime")
    # Arbitrary command execution — the highest-risk tool.
    risk_level = "high"

    # Injected from Role by bind() — the stable-cwd accessor plus the optional
    # OS-level sandbox runtime accessor, never RoleState or memory.
    get_cwd: Callable[[], str]
    # Capability accessor returning the session's SandboxRuntime, or None when
    # no OS-level sandbox is configured. Defaults to a no-runtime stub so a
    # tool bound without a Role (some unit tests) still runs un-sandboxed.
    get_sandbox_runtime: Callable[[], object] = staticmethod(lambda: None)

    def permission_target(self, args: dict) -> str:
        """The command string — matched against ``Bash(pattern)`` rules."""
        return args.get("command") or ""

    def permission_segments(self, args: dict) -> "list[str] | None":
        """Split the command on shell operators for per-segment rule matching."""
        command = args.get("command") or ""
        return segment_strings(command) or None

    def check_permissions(self, args: dict) -> "PermissionDecision | None":
        """Classify the command and short-circuit the obvious cases.

        Uses the shared :func:`classify_command` (Codex-style safety pre-check):

          * destructive (``rm -rf``, ``mkfs``, ``sudo`` ...) -> ``ask``
            (bypass-immune — forces a prompt regardless of allow rules / mode);
          * verifiably read-only (``ls``, ``cat``, ``git status`` ...) ->
            ``allow`` (auto-approved, no prompt in ``default`` mode);
          * anything unrecognised -> ``None`` to defer to rules/mode.
        """
        command = args.get("command") or ""
        assessment = classify_command(command)
        if assessment.risk == "high":
            return PermissionDecision.ask(
                "tool_check",
                "potentially destructive command",
                message=f"This command looks destructive: {command}",
            )
        if assessment.known_safe:
            return PermissionDecision.allow("tool_check", assessment.reason)
        return None

    async def call(self, *, command: str, timeout: float = 300.0, workdir: str = "") -> str:
        """Execute a bash command against the session's stable working directory.

        Args:
            command: The bash command to execute.
            timeout: Maximum seconds to wait for the command (default 300). On
                timeout the command is terminated and whatever output it produced
                so far is returned (rather than raising), mirroring codex.
            workdir: Optional directory to run this one command in. Relative
                paths resolve against the session's stable working directory.
                Use this to operate in a subdirectory — a ``cd`` inside the
                command does NOT persist across calls (the cwd is a stable value,
                not shell state), so ``workdir`` is the way to scope a command to
                another directory.
        """
        if not command or not command.strip():
            raise ToolError(_MSG_COMMAND_REQUIRED)

        cwd = self.get_cwd()
        base_cwd = cwd if cwd and os.path.isdir(cwd) else None

        # `workdir` scopes this one command to a directory (relative paths
        # resolve against the stable base cwd). Without it we run in the stable
        # base cwd. Either way the session's cwd is never mutated — a `cd` inside
        # the command does not persist (Codex-aligned: cwd is data, not state).
        if workdir:
            run_cwd = workdir if os.path.isabs(workdir) else os.path.join(base_cwd or os.getcwd(), workdir)
            if not os.path.isdir(run_cwd):
                raise ToolError(_MSG_WORKDIR_NOT_EXIST.format(workdir=workdir))
        else:
            run_cwd = base_cwd  # may be None -> aexecute uses the process default

        # OS-level sandbox: when a runtime is wired, aexecute wraps the command
        # (bwrap + hardening) and amends the env before spawning. None => the
        # historical un-sandboxed path.
        runtime = self.get_sandbox_runtime() if self.get_sandbox_runtime is not None else None

        try:
            # return_partial_on_timeout=True always yields the 4-tuple
            # (rc, stdout, stderr, timed_out); narrow the declared union.
            rc, stdout, stderr, timed_out = cast(
                "tuple[int, str, str, bool]",
                await aexecute(
                    command,
                    working_dir=run_cwd,
                    wait=True,
                    timeout=timeout,
                    return_partial_on_timeout=True,
                    sandbox_runtime=runtime,
                ),
            )
        except Exception as e:
            raise ToolError(_MSG_EXEC_FAILED.format(error=e))

        output = stdout.rstrip("\n") if stdout else ""
        parts = []
        if timed_out:
            parts.append(f"command timed out after {int(timeout * 1000)} milliseconds")
        if output:
            parts.append(output)
        if stderr:
            parts.append(stderr)
        if not timed_out and rc:
            parts.append(f"[exit code: {rc}]")
        return "\n".join(parts) if parts else ""

    def cleanup_session(self, session_id: str) -> None:
        """No persistent process to tear down; aexecute spawns per-call."""
