"""Authoritative static architecture gate declarations."""

from mote.contracts.composition.gates import CheckerStatus, GateDeclaration

_STATIC = "python -B ztest/architecture/static_governance.py {check}"

GATE_DECLARATIONS = (
    GateDeclaration(
        "ARCH-LOCAL-IMPORT",
        "Python AST",
        "pytest-local-imports",
        CheckerStatus.PRESENT,
        _STATIC.format(check="local-imports"),
        "architecture-owner",
        "always",
    ),
    GateDeclaration(
        "PRODUCT-IMPORT-SCC",
        "Python imports",
        "pytest-product-scc",
        CheckerStatus.PRESENT,
        _STATIC.format(check="product-scc"),
        "product-architecture-owner",
        "expected SCC sets are empty",
    ),
    GateDeclaration(
        "TYPE-TELEMETRY-ERASURE",
        "typed telemetry boundary",
        "telemetry-erasure",
        CheckerStatus.PRESENT,
        _STATIC.format(check="telemetry-erasure"),
        "runtime-telemetry-owner",
        "raw caller set is empty",
    ),
    GateDeclaration(
        "EVENT-FACT-ADMISSION",
        "codec declarations and Python AST",
        "event-fact-admission",
        CheckerStatus.PRESENT,
        _STATIC.format(check="fact-admission"),
        "event-runtime-owners",
        "business construction set is empty",
    ),
    GateDeclaration(
        "PRODUCT-OWNER-EXPORT",
        "owner declarations and source exports",
        "product-owner-export",
        CheckerStatus.PRESENT,
        "python -B ztest/architecture/composition_governance.py",
        "product-architecture-owner",
        "owner scope resolution is closed",
    ),
    GateDeclaration(
        "CAP-REACHABILITY",
        "candidate classifications and composition declarations",
        "capability-reachability",
        CheckerStatus.PRESENT,
        "python -B ztest/architecture/composition_governance.py",
        "product-composition-owner",
        "candidate/declaration bidirectional difference is empty",
    ),
    GateDeclaration(
        "STORE-CUTOVER",
        "active store declarations and cutover state validation",
        "store-cutover",
        CheckerStatus.PRESENT,
        "python -B ztest/architecture/store_cutover.py",
        "store-owners",
        "persistent fence, history replay, quiesce and activation evidence are executable",
        "cutover-status-v1",
    ),
    GateDeclaration(
        "RESTORE-ADMISSION",
        "restore inventory and isolated conversion authority",
        "restore-admission",
        CheckerStatus.PRESENT,
        "python -B ztest/architecture/restore_admission.py",
        "store-owners",
        "source-derived restore inventory is closed and every copy is controlled",
        "restore-status-v1",
    ),
    GateDeclaration(
        "MIGRATION-DEBT",
        "typed migration debt declarations",
        "migration-debt",
        CheckerStatus.PRESENT,
        "python -B ztest/architecture/unique_production_path.py",
        "domain-owners",
        "storage evidence proves production migration debt is empty",
        "migration-debt-status-v1",
    ),
    GateDeclaration(
        "DYNAMIC-DISCOVERY",
        "Application catalogs and Python AST",
        "dynamic-discovery-diff",
        CheckerStatus.PRESENT,
        _STATIC.format(check="dynamic-discovery"),
        "product-composition-owner",
        "legacy discovery set is empty",
    ),
    GateDeclaration(
        "EVENT-TRANSFORMATION",
        "codec, translator and subscription declarations plus Python AST",
        "event-transformation-closure",
        CheckerStatus.PRESENT,
        "python -B ztest/architecture/event_governance.py",
        "event-runtime-owners",
        "all stage crossings and durable codecs are source-derived and uniquely owned",
    ),
    GateDeclaration(
        "DURABLE-POLICY",
        "codec storage policy and durable payload validators",
        "durable-policy-security-retention",
        CheckerStatus.PRESENT,
        "python -B ztest/architecture/durable_policy.py",
        "event-runtime-owners",
        "security, retention, redaction, size and secondary-copy checks are complete",
    ),
    GateDeclaration(
        "SUBSCRIPTION-RELIABILITY",
        "subscription specs, handler effect policy and state-store transaction semantics",
        "subscription-reliability",
        CheckerStatus.PRESENT,
        "python -B ztest/architecture/subscription_reliability.py",
        "event-runtime-owners",
        "recoverable checkpoint, quarantine and side-effect invariants are executable",
    ),
    GateDeclaration(
        "UNIQUE-PRODUCTION-PATH",
        "typed production-path and migration-debt classification",
        "unique-production-path",
        CheckerStatus.PRESENT,
        "python -B ztest/architecture/unique_production_path.py",
        "architecture-owner",
        "source-derived double-path and typed debt sets are empty",
    ),
    GateDeclaration(
        "WIRE-AUTHORITY",
        "per-API wire authority and one-way derivation declarations",
        "wire-authority-conformance",
        CheckerStatus.PRESENT,
        "python -B ztest/architecture/wire_authority.py",
        "product-integration-owners",
        "every governed wire API has one authority and one-way conformance",
    ),
    GateDeclaration(
        "DERIVED-ARTIFACT",
        "typed authority and deterministic generator declarations",
        "derived-artifact-conformance",
        CheckerStatus.PRESENT,
        _STATIC.format(check="derived-artifact"),
        "architecture-owner",
        "all committed governance artifacts are fresh",
    ),
    GateDeclaration(
        "TYPE-GOVERNED-BOUNDARY",
        "governed public annotations and Python AST",
        "governed-boundary-any",
        CheckerStatus.PRESENT,
        _STATIC.format(check="governed-boundary"),
        "architecture-owner",
        "governed public Any set is empty",
    ),
)

__all__ = ["GATE_DECLARATIONS"]
