#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""``mote.product.presentation.events`` — the shared human-protocol contract.

The ``ViewEvent`` tagged union (:mod:`~mote.product.presentation.events.events`) plus the
declarative capability bits + per-consumer downgrade adapter
(:mod:`~mote.product.presentation.events.capabilities`). These are the *cross-host*
contracts — every host that renders for a person shares them — so they sit in
the shared ``contracts`` layer, while the concrete ``AgentEvent → ViewEvent`` fold
(``ViewProjector``) stays host-side in :mod:`mote.product.presentation.projection`.
"""

from mote.product.presentation.events.capabilities import (
    STRUCTURED_CAPS,
    TERMINAL_CAPS,
    TEXTUAL_CAPS,
    Capabilities,
    CapabilityAdapter,
)
from mote.product.presentation.events.events import (
    ACTIVITY_COMPLETED,
    ACTIVITY_STARTED,
    APPROVAL_REQUESTED,
    ARTIFACT_BLOCK,
    ASYNC_WORK_OBSERVED,
    ATTEMPT_STREAM_COMMITTED,
    ATTEMPT_STREAM_DISCARDED,
    ATTEMPT_STREAM_INTERRUPTED,
    CONVERSATION_COMPACTED,
    ERROR_RAISED,
    FILE_DIFF_BLOCK,
    MEDIA_BLOCK,
    MESSAGE_BLOCK_COMPLETED,
    MESSAGE_BLOCK_DELTA,
    MESSAGE_BLOCK_STARTED,
    NOTICE,
    QUESTION_ASKED,
    REASONING_DELTA,
    RESULT_KIND_DIFF,
    RESULT_KIND_MEDIA,
    RESULT_KIND_PLAIN,
    RESULT_KIND_TABLE,
    RETRY_STATUS,
    RUNTIME_DURABILITY_STATUS,
    SESSION_LIST_SHOWN,
    SYSTEM_REMINDER,
    TASK_PROGRESS,
    TOOL_CALL_COMPLETED,
    TOOL_CALL_STARTED,
    TRANSCRIPT_CLEARED,
    USAGE_UPDATED,
    ActivityCompleted,
    ActivityStarted,
    ApprovalDecision,
    ApprovalRequested,
    ArtifactBlock,
    AsyncWorkObserved,
    AttemptStreamCommitted,
    AttemptStreamDiscarded,
    AttemptStreamInterrupted,
    ConversationCompacted,
    ErrorRaised,
    FileDiffBlock,
    MediaBlock,
    MessageBlockCompleted,
    MessageBlockDelta,
    MessageBlockStarted,
    Notice,
    QuestionAsked,
    ReasoningDelta,
    RetryStatus,
    RuntimeDurabilityStatus,
    SessionListItem,
    SessionListShown,
    SystemReminder,
    SystemReminderLifetime,
    TaskProgress,
    ToolCallCompleted,
    ToolCallStarted,
    TranscriptCleared,
    UsageUpdated,
    UserMediaIdentity,
    ViewEvent,
)
from mote.product.presentation.events.folding import GROUP_READ_TOOLS, GROUP_SEARCH_TOOLS, FoldMode, fold_mode

__all__ = [
    "FoldMode",
    "GROUP_READ_TOOLS",
    "GROUP_SEARCH_TOOLS",
    "fold_mode",
    "ViewEvent",
    "MessageBlockStarted",
    "MessageBlockDelta",
    "MessageBlockCompleted",
    "AttemptStreamCommitted",
    "AttemptStreamDiscarded",
    "AttemptStreamInterrupted",
    "ReasoningDelta",
    "ToolCallStarted",
    "ToolCallCompleted",
    "MediaBlock",
    "UserMediaIdentity",
    "ArtifactBlock",
    "FileDiffBlock",
    "TaskProgress",
    "Notice",
    "ErrorRaised",
    "QuestionAsked",
    "ApprovalRequested",
    "ApprovalDecision",
    "UsageUpdated",
    "SessionListItem",
    "SessionListShown",
    "RetryStatus",
    "RuntimeDurabilityStatus",
    "TranscriptCleared",
    "SystemReminder",
    "SystemReminderLifetime",
    "ConversationCompacted",
    "ActivityStarted",
    "AsyncWorkObserved",
    "ASYNC_WORK_OBSERVED",
    "ActivityCompleted",
    "MESSAGE_BLOCK_STARTED",
    "MESSAGE_BLOCK_DELTA",
    "MESSAGE_BLOCK_COMPLETED",
    "ATTEMPT_STREAM_COMMITTED",
    "ATTEMPT_STREAM_DISCARDED",
    "ATTEMPT_STREAM_INTERRUPTED",
    "REASONING_DELTA",
    "TOOL_CALL_STARTED",
    "TOOL_CALL_COMPLETED",
    "MEDIA_BLOCK",
    "ARTIFACT_BLOCK",
    "FILE_DIFF_BLOCK",
    "TASK_PROGRESS",
    "NOTICE",
    "ERROR_RAISED",
    "QUESTION_ASKED",
    "APPROVAL_REQUESTED",
    "USAGE_UPDATED",
    "SESSION_LIST_SHOWN",
    "RETRY_STATUS",
    "RUNTIME_DURABILITY_STATUS",
    "TRANSCRIPT_CLEARED",
    "SYSTEM_REMINDER",
    "CONVERSATION_COMPACTED",
    "ACTIVITY_STARTED",
    "ACTIVITY_COMPLETED",
    "RESULT_KIND_PLAIN",
    "RESULT_KIND_DIFF",
    "RESULT_KIND_TABLE",
    "RESULT_KIND_MEDIA",
    "Capabilities",
    "CapabilityAdapter",
    "TERMINAL_CAPS",
    "TEXTUAL_CAPS",
    "STRUCTURED_CAPS",
]
