"""Inference checkpoint lifecycle port."""

from typing import TYPE_CHECKING, Protocol

from mote.contracts.execution.models import InferenceCheckpointState

if TYPE_CHECKING:
    from mote.contracts.events.model import InferenceCheckpointConsumedEvent


class InferenceCheckpointPort(Protocol):
    async def reinstate(self) -> bool: ...

    def resume(self) -> InferenceCheckpointState | None: ...

    def begin_call(self, state: InferenceCheckpointState) -> None: ...

    def refresh(self, state: InferenceCheckpointState) -> None: ...

    def mark_wire_started(self) -> None: ...

    async def record_result(self) -> None: ...

    async def prepare_consumption(self, operation_id: str) -> "InferenceCheckpointConsumedEvent": ...

    def acknowledge_consumption(self, event: "InferenceCheckpointConsumedEvent") -> None: ...

    def discard(self) -> None: ...

    def abort(self) -> None: ...


__all__ = ["InferenceCheckpointPort"]
